=== eashman/nist-hl7-core/core-xml-beans/src/main/xsd/MessageValidationCorrelation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by Sydney (NIST) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.nist.gov/healthcare/validation/message/hl7/context" xmlns:xml="http://www.w3.org/XML/1998/namespace" targetNamespace="http://www.nist.gov/healthcare/validation/message/hl7/context" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="MessageValidationCorrelation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Correlations">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="Correlation">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="SingleValue" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Between" type="xs:string"/>
													<xs:element name="And">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute name="messageKey" type="xs:string" use="required"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="optional" type="xs:boolean"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="Copy" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Source">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute name="messageKey" type="xs:string" use="required"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== eashman/nist-hl7-core/core-message-validation/src/test/resources/content/v2/TestMultiMessageCorrelationDocument.xml
<MessageValidationCorrelation xmlns="http://www.nist.gov/healthcare/validation/message/hl7/context" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nist.gov/healthcare/validation/message/hl7/context file:///D:/home/svn/core-maven/trunk/core-xml-beans/src/main/xsd/MessageValidationCorrelation.xsd">
	<Correlations>
		<Correlation>
			<SingleValue>
				<Between>MSH[1].3[1].1</Between>
				<And messageKey="query">MSH[1].5[1].1</And>
			</SingleValue>
			<SingleValue>
				<Between>MSH[1].4[1].1</Between>
				<And messageKey="query">MSH[1].6[1].1</And>
			</SingleValue>
			<SingleValue>
				<Between>MSH[1].5[1].1</Between>
				<And messageKey="query">MSH[1].3[1].1</And>
			</SingleValue>
			<SingleValue>
				<Between>MSH[1].6[1].1</Between>
				<And messageKey="query">MSH[1].4[1].1</And>
			</SingleValue>
			<Copy>
				<Source messageKey="query">QPD[1]</Source>
			</Copy>
		</Correlation>
	</Correlations>
</MessageValidationCorrelation>

=== eashman/nist-hl7-core/core-message-validation/src/test/resources/content/v3/TestMultiMessageCorrelationDocument.xml
<MessageValidationCorrelation xmlns="http://www.nist.gov/healthcare/validation/message/hl7/context" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nist.gov/healthcare/validation/message/hl7/context file:///D:/home/svn/core-maven/trunk/core-xml-beans/src/main/xsd/MessageValidationCorrelation.xsd">
	<Correlations>
		<Correlation>
			<SingleValue>
				<Between>//*:receiver/*:device/*:id/@root</Between>
				<And messageKey="query">//*:sender/*:device/*:id/@root</And>
			</SingleValue>
			<SingleValue optional="true">
				<Between>//*:receiver/*:device/*:asAgent/*:representedOrganization/*:id/@root</Between>
				<And messageKey="query">//*:sender/*:device/*:asAgent/*:representedOrganization/*:id/@root</And>
			</SingleValue>
			<SingleValue>
				<Between>//*:sender/*:device/*:id/@root</Between>
				<And messageKey="query">//*:receiver/*:device/*:id/@root</And>
			</SingleValue>
			<SingleValue optional="true">
				<Between>//*:sender/*:device/*:asAgent/*:representedOrganization/*:id/@root</Between>
				<And messageKey="query">//*:receiver/*:device/*:asAgent/*:representedOrganization/*:id/@root</And>
			</SingleValue>
			<Copy>
				<Source messageKey="query">//*:controlActProcess/*:queryByParameter</Source>
			</Copy>
		</Correlation>
	</Correlations>
</MessageValidationCorrelation>
